version: '3'

###
# TDM
###

services:
  tdm:
    image: unidata/tdm-docker:5.0-SNAPSHOT
    container_name: tdm
    volumes:
      - /path/to/your/thredds/directory:/usr/local/tomcat/content/thredds
      - /path/to/your/data/directory1:/path/to/your/data/directory1
      # TDM logging non-configurable until 5.0 so you'll need tdm.sh and
      # tdm.jar if you want to log outside the container :-(
      - /path/to/your/tdm/logs:/usr/local/tomcat/content/tdm/
    env_file:
      - "compose.env"
