---
version: '3'

volumes:
  tdm-volume:

networks:
  thredds-network:

services:
  tdm:
    image: unidata/tdm-docker:4.6
    container_name: tdm
    volumes:
      - tdm-volume:/usr/local/tomcat/content/thredds/
      # - /path/to/your/thredds/directory:/usr/local/tomcat/content/thredds
      - tdm-volume:/usr/local/tomcat/content/tdm/
    networks:
      thredds-network:
        aliases:
          - tdm
    environment:
      # change the password
      - TDM_PW=CHANGEME!
      # that trailing slash is important
      - TDS_HOST=http://thredds.yourhost.net/
