version: '3'

services:
  tdm:
    image: unidata/tdm-docker:5.4
    container_name: tdm
    volumes:
      - /path/to/your/thredds/directory:/usr/local/tomcat/content/thredds
      - /path/to/your/data/directory1:/path/to/your/data/directory1
    env_file:
      - "compose${THREDDS_COMPOSE_ENV_LOCAL}.env"
