version: '3'

###
# TDM
###

services:
  tdm:
    image: unidata/tdm-docker:5.0-beta9
    container_name: tdm
    volumes:
      - /path/to/your/thredds/directory:/usr/local/tomcat/content/thredds
      - /path/to/your/data/directory1:/path/to/your/data/directory1
      - /path/to/your/tdm/logs:/usr/local/tomcat/content/tdm/logs
    env_file:
      - "compose.env"
